/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  collection?: string;
  subtitle?: string;
  garment?: string;
  tagline?: string;
  price: number;
  front: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  back: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  variants?: Array<{
    size?: "XS" | "S" | "M" | "L" | "XL" | "XXL";
    stock?: number;
    _type: "variant";
    _key: string;
  }>;
  description?: string;
  available?: boolean;
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type FootageAsset = {
  _id: string;
  _type: "footageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  location?: string;
  duration?: string;
  fps?: number;
  resolution?: "4K" | "HD";
  poster: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  previewUrl?: string;
  downloadUrl?: string;
  licence?: string;
  featured?: boolean;
  order?: number;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  category: string;
  publishedAt: string;
  cover: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  excerpt: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  author?: string;
};

export type Client = {
  _id: string;
  _type: "client";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  url?: string;
  order?: number;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  category: string;
  timecode?: string;
  still: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  videoUrl?: string;
  featured?: boolean;
  order?: number;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  tag: string;
  timecode?: string;
  description: string;
  order?: number;
};

export type SectionIntro = {
  _type: "sectionIntro";
  eyebrow: string;
  heading: string;
  linkLabel?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  phone?: string;
  address?: string;
  addressShort?: string;
  hoursSummary?: string;
  hours?: Array<{
    days?: string;
    time?: string;
    _type: "hoursRow";
    _key: string;
  }>;
  socials?: Array<{
    platform?: "YouTube" | "Instagram" | "Facebook" | "LinkedIn" | "X" | "TikTok";
    url?: string;
    _type: "social";
    _key: string;
  }>;
  footerBlurb?: string;
  copyrightName?: string;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroHeadline: Array<string>;
  heroHighlight?: string;
  heroIntro?: string;
  heroPrimaryCta?: string;
  heroSecondaryCta?: string;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  heroVideoUrl?: string;
  stats?: Array<{
    value?: string;
    label?: string;
    _type: "stat";
    _key: string;
  }>;
  services: SectionIntro;
  servicesCta?: string;
  projects: SectionIntro;
  clientsHeading?: string;
  updates: SectionIntro;
  updatesReadMore?: string;
  footage: SectionIntro;
  footageDownload?: string;
  merch: SectionIntro;
  contact: SectionIntro;
  contactIntro?: string;
  contactFormHeading?: string;
  contactSubmit?: string;
  contactImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Product
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | FootageAsset
  | Post
  | Client
  | Project
  | Service
  | SectionIntro
  | SiteSettings
  | HomePage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries.ts
// Variable: homepageQuery
// Query: {  "page": *[_id == "homePage"][0],  "settings": *[_id == "siteSettings"][0],  "services": *[_type == "service"] | order(order asc),  "projects": *[_type == "project" && featured] | order(order asc)[0...4],  "clients": *[_type == "client"] | order(order asc),  "posts": *[_type == "post"] | order(publishedAt desc)[0...3],  "footage": *[_type == "footageAsset"] | order(featured desc, order asc)[0...4],  "products": *[_type == "product"] | order(order asc)}
export type HomepageQueryResult = {
  page:
    | {
        _id: "homePage";
        _type: "client";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        name: string;
        logo: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
        };
        url?: string;
        order?: number;
      }
    | {
        _id: "homePage";
        _type: "footageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        title: string;
        location?: string;
        duration?: string;
        fps?: number;
        resolution?: "4K" | "HD";
        poster: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
        };
        previewUrl?: string;
        downloadUrl?: string;
        licence?: string;
        featured?: boolean;
        order?: number;
      }
    | {
        _id: "homePage";
        _type: "homePage";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        heroEyebrow?: string;
        heroHeadline: Array<string>;
        heroHighlight?: string;
        heroIntro?: string;
        heroPrimaryCta?: string;
        heroSecondaryCta?: string;
        heroImage: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
        };
        heroVideoUrl?: string;
        stats?: Array<{
          value?: string;
          label?: string;
          _type: "stat";
          _key: string;
        }>;
        services: SectionIntro;
        servicesCta?: string;
        projects: SectionIntro;
        clientsHeading?: string;
        updates: SectionIntro;
        updatesReadMore?: string;
        footage: SectionIntro;
        footageDownload?: string;
        merch: SectionIntro;
        contact: SectionIntro;
        contactIntro?: string;
        contactFormHeading?: string;
        contactSubmit?: string;
        contactImage: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
        };
      }
    | {
        _id: "homePage";
        _type: "post";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        title: string;
        slug: Slug;
        category: string;
        publishedAt: string;
        cover: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
        };
        excerpt: string;
        body?: Array<
          | {
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
              listItem?: "bullet" | "number";
              markDefs?: Array<{
                href?: string;
                _type: "link";
                _key: string;
              }>;
              level?: number;
              _type: "block";
              _key: string;
            }
          | {
              asset?: SanityImageAssetReference;
              media?: unknown;
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              _type: "image";
              _key: string;
            }
        >;
        author?: string;
      }
    | {
        _id: "homePage";
        _type: "product";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        name: string;
        slug: Slug;
        collection?: string;
        subtitle?: string;
        garment?: string;
        tagline?: string;
        price: number;
        front: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
        };
        back: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
        };
        variants?: Array<{
          size?: "L" | "M" | "S" | "XL" | "XS" | "XXL";
          stock?: number;
          _type: "variant";
          _key: string;
        }>;
        description?: string;
        available?: boolean;
        order?: number;
      }
    | {
        _id: "homePage";
        _type: "project";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        title: string;
        category: string;
        timecode?: string;
        still: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
        };
        videoUrl?: string;
        featured?: boolean;
        order?: number;
      }
    | {
        _id: "homePage";
        _type: "sanity.fileAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash: string;
        extension: string;
        mimeType: string;
        size: number;
        assetId: string;
        uploadId?: string;
        path: string;
        url: string;
        source?: SanityAssetSourceData;
      }
    | {
        _id: "homePage";
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash: string;
        extension: string;
        mimeType: string;
        size: number;
        assetId: string;
        uploadId?: string;
        path: string;
        url: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      }
    | {
        _id: "homePage";
        _type: "service";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        title: string;
        tag: string;
        timecode?: string;
        description: string;
        order?: number;
      }
    | {
        _id: "homePage";
        _type: "siteSettings";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        email?: string;
        phone?: string;
        address?: string;
        addressShort?: string;
        hoursSummary?: string;
        hours?: Array<{
          days?: string;
          time?: string;
          _type: "hoursRow";
          _key: string;
        }>;
        socials?: Array<{
          platform?: "Facebook" | "Instagram" | "LinkedIn" | "TikTok" | "X" | "YouTube";
          url?: string;
          _type: "social";
          _key: string;
        }>;
        footerBlurb?: string;
        copyrightName?: string;
      }
    | null;
  settings:
    | {
        _id: "siteSettings";
        _type: "client";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        name: string;
        logo: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
        };
        url?: string;
        order?: number;
      }
    | {
        _id: "siteSettings";
        _type: "footageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        title: string;
        location?: string;
        duration?: string;
        fps?: number;
        resolution?: "4K" | "HD";
        poster: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
        };
        previewUrl?: string;
        downloadUrl?: string;
        licence?: string;
        featured?: boolean;
        order?: number;
      }
    | {
        _id: "siteSettings";
        _type: "homePage";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        heroEyebrow?: string;
        heroHeadline: Array<string>;
        heroHighlight?: string;
        heroIntro?: string;
        heroPrimaryCta?: string;
        heroSecondaryCta?: string;
        heroImage: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
        };
        heroVideoUrl?: string;
        stats?: Array<{
          value?: string;
          label?: string;
          _type: "stat";
          _key: string;
        }>;
        services: SectionIntro;
        servicesCta?: string;
        projects: SectionIntro;
        clientsHeading?: string;
        updates: SectionIntro;
        updatesReadMore?: string;
        footage: SectionIntro;
        footageDownload?: string;
        merch: SectionIntro;
        contact: SectionIntro;
        contactIntro?: string;
        contactFormHeading?: string;
        contactSubmit?: string;
        contactImage: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
        };
      }
    | {
        _id: "siteSettings";
        _type: "post";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        title: string;
        slug: Slug;
        category: string;
        publishedAt: string;
        cover: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
        };
        excerpt: string;
        body?: Array<
          | {
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
              listItem?: "bullet" | "number";
              markDefs?: Array<{
                href?: string;
                _type: "link";
                _key: string;
              }>;
              level?: number;
              _type: "block";
              _key: string;
            }
          | {
              asset?: SanityImageAssetReference;
              media?: unknown;
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              _type: "image";
              _key: string;
            }
        >;
        author?: string;
      }
    | {
        _id: "siteSettings";
        _type: "product";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        name: string;
        slug: Slug;
        collection?: string;
        subtitle?: string;
        garment?: string;
        tagline?: string;
        price: number;
        front: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
        };
        back: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
        };
        variants?: Array<{
          size?: "L" | "M" | "S" | "XL" | "XS" | "XXL";
          stock?: number;
          _type: "variant";
          _key: string;
        }>;
        description?: string;
        available?: boolean;
        order?: number;
      }
    | {
        _id: "siteSettings";
        _type: "project";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        title: string;
        category: string;
        timecode?: string;
        still: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
        };
        videoUrl?: string;
        featured?: boolean;
        order?: number;
      }
    | {
        _id: "siteSettings";
        _type: "sanity.fileAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash: string;
        extension: string;
        mimeType: string;
        size: number;
        assetId: string;
        uploadId?: string;
        path: string;
        url: string;
        source?: SanityAssetSourceData;
      }
    | {
        _id: "siteSettings";
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash: string;
        extension: string;
        mimeType: string;
        size: number;
        assetId: string;
        uploadId?: string;
        path: string;
        url: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      }
    | {
        _id: "siteSettings";
        _type: "service";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        title: string;
        tag: string;
        timecode?: string;
        description: string;
        order?: number;
      }
    | {
        _id: "siteSettings";
        _type: "siteSettings";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        email?: string;
        phone?: string;
        address?: string;
        addressShort?: string;
        hoursSummary?: string;
        hours?: Array<{
          days?: string;
          time?: string;
          _type: "hoursRow";
          _key: string;
        }>;
        socials?: Array<{
          platform?: "Facebook" | "Instagram" | "LinkedIn" | "TikTok" | "X" | "YouTube";
          url?: string;
          _type: "social";
          _key: string;
        }>;
        footerBlurb?: string;
        copyrightName?: string;
      }
    | null;
  services: Array<{
    _id: string;
    _type: "service";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string;
    tag: string;
    timecode?: string;
    description: string;
    order?: number;
  }>;
  projects: Array<{
    _id: string;
    _type: "project";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string;
    category: string;
    timecode?: string;
    still: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    videoUrl?: string;
    featured?: boolean;
    order?: number;
  }>;
  clients: Array<{
    _id: string;
    _type: "client";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name: string;
    logo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    url?: string;
    order?: number;
  }>;
  posts: Array<{
    _id: string;
    _type: "post";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string;
    slug: Slug;
    category: string;
    publishedAt: string;
    cover: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    excerpt: string;
    body?: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          _key: string;
        }
    >;
    author?: string;
  }>;
  footage: Array<{
    _id: string;
    _type: "footageAsset";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string;
    location?: string;
    duration?: string;
    fps?: number;
    resolution?: "4K" | "HD";
    poster: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    previewUrl?: string;
    downloadUrl?: string;
    licence?: string;
    featured?: boolean;
    order?: number;
  }>;
  products: Array<{
    _id: string;
    _type: "product";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name: string;
    slug: Slug;
    collection?: string;
    subtitle?: string;
    garment?: string;
    tagline?: string;
    price: number;
    front: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    back: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    variants?: Array<{
      size?: "L" | "M" | "S" | "XL" | "XS" | "XXL";
      stock?: number;
      _type: "variant";
      _key: string;
    }>;
    description?: string;
    available?: boolean;
    order?: number;
  }>;
};
