/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  collection?: string;
  subtitle?: string;
  garment?: string;
  tagline?: string;
  price: number;
  front: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  back: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  variants?: Array<{
    size?: "XS" | "S" | "M" | "L" | "XL" | "XXL";
    stock?: number;
    _type: "variant";
    _key: string;
  }>;
  description?: string;
  available?: boolean;
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type FootageAsset = {
  _id: string;
  _type: "footageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  location?: string;
  duration?: string;
  fps?: number;
  resolution?: "4K" | "HD";
  poster: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  previewUrl?: string;
  downloadUrl?: string;
  licence?: string;
  featured?: boolean;
  order?: number;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  category: string;
  publishedAt: string;
  cover: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  excerpt: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  author?: string;
};

export type Client = {
  _id: string;
  _type: "client";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  logoHeight?: number;
  url?: string;
  order?: number;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  category: string;
  timecode?: string;
  still: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  videoUrl?: string;
  featured?: boolean;
  order?: number;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  tag: string;
  timecode?: string;
  description: string;
  order?: number;
};

export type SectionIntro = {
  _type: "sectionIntro";
  eyebrow: string;
  heading: string;
  linkLabel?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  phone?: string;
  address?: string;
  addressShort?: string;
  location?: {
    latitude?: number;
    longitude?: number;
  };
  hoursSummary?: string;
  hours?: Array<{
    days?: string;
    time?: string;
    _type: "hoursRow";
    _key: string;
  }>;
  socials?: Array<{
    platform?: "YouTube" | "Instagram" | "Facebook" | "LinkedIn" | "X" | "TikTok";
    url?: string;
    _type: "social";
    _key: string;
  }>;
  footerBlurb?: string;
  copyrightName?: string;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroHeadline: Array<string>;
  heroHighlight?: string;
  heroIntro?: string;
  heroPrimaryCta?: string;
  heroSecondaryCta?: string;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  heroVideoUrl?: string;
  stats?: Array<{
    value?: string;
    label?: string;
    _type: "stat";
    _key: string;
  }>;
  services: SectionIntro;
  servicesCta?: string;
  projects: SectionIntro;
  clientsHeading?: string;
  updates: SectionIntro;
  updatesReadMore?: string;
  footage: SectionIntro;
  footageDownload?: string;
  merch: SectionIntro;
  contact: SectionIntro;
  contactIntro?: string;
  contactFormHeading?: string;
  contactSubmit?: string;
  contactImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  seoTitle?: string;
  seoDescription?: string;
  shareImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Product
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | FootageAsset
  | Post
  | Client
  | Project
  | Service
  | SectionIntro
  | SiteSettings
  | HomePage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries.ts
// Variable: homepageQuery
// Query: {  "page": *[_type == "homePage" && _id == "homePage"][0]{    heroEyebrow, heroHeadline, heroHighlight, heroIntro, heroPrimaryCta, heroSecondaryCta,    heroImage, heroVideoUrl, stats,    services, servicesCta,    projects,    clientsHeading,    updates, updatesReadMore,    footage, footageDownload,    merch,    contact, contactIntro, contactFormHeading, contactSubmit, contactImage  },  "services": *[_type == "service"] | order(order asc){ _id, title, tag, timecode, description },  "projects": *[_type == "project" && featured == true] | order(order asc)[0...4]{    _id, title, category, timecode, still, videoUrl  },  "clients": *[_type == "client"] | order(order asc){    _id, name, url, logoHeight,    logo{ ..., "dimensions": asset->metadata.dimensions{ width, height } }  },  "posts": *[_type == "post"] | order(publishedAt desc)[0...3]{    _id, title, "slug": slug.current, category, publishedAt, cover, excerpt  },  "footage": *[_type == "footageAsset"] | order(featured desc, order asc)[0...4]{    _id, title, location, duration, fps, resolution, poster, downloadUrl, featured  },  "products": *[_type == "product"] | order(order asc)[0...2]{    _id, name, garment, price, "slug": slug.current, front, back, available  }}
export type HomepageQueryResult = {
  page: {
    heroEyebrow: string | null;
    heroHeadline: Array<string>;
    heroHighlight: string | null;
    heroIntro: string | null;
    heroPrimaryCta: string | null;
    heroSecondaryCta: string | null;
    heroImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    heroVideoUrl: string | null;
    stats: Array<{
      value?: string;
      label?: string;
      _type: "stat";
      _key: string;
    }> | null;
    services: SectionIntro;
    servicesCta: string | null;
    projects: SectionIntro;
    clientsHeading: string | null;
    updates: SectionIntro;
    updatesReadMore: string | null;
    footage: SectionIntro;
    footageDownload: string | null;
    merch: SectionIntro;
    contact: SectionIntro;
    contactIntro: string | null;
    contactFormHeading: string | null;
    contactSubmit: string | null;
    contactImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
  } | null;
  services: Array<{
    _id: string;
    title: string;
    tag: string;
    timecode: string | null;
    description: string;
  }>;
  projects: Array<{
    _id: string;
    title: string;
    category: string;
    timecode: string | null;
    still: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    videoUrl: string | null;
  }>;
  clients: Array<{
    _id: string;
    name: string;
    url: string | null;
    logoHeight: number | null;
    logo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
      dimensions: {
        width: number;
        height: number;
      } | null;
    };
  }>;
  posts: Array<{
    _id: string;
    title: string;
    slug: string;
    category: string;
    publishedAt: string;
    cover: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    excerpt: string;
  }>;
  footage: Array<{
    _id: string;
    title: string;
    location: string | null;
    duration: string | null;
    fps: number | null;
    resolution: "4K" | "HD" | null;
    poster: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    downloadUrl: string | null;
    featured: boolean | null;
  }>;
  products: Array<{
    _id: string;
    name: string;
    garment: string | null;
    price: number;
    slug: string;
    front: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    back: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    available: boolean | null;
  }>;
};

// Source: src/sanity/queries.ts
// Variable: seoQuery
// Query: *[_type == "homePage" && _id == "homePage"][0]{  seoTitle, seoDescription, shareImage, heroImage, heroIntro, heroHeadline, heroHighlight}
export type SeoQueryResult = {
  seoTitle: string | null;
  seoDescription: string | null;
  shareImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  heroIntro: string | null;
  heroHeadline: Array<string>;
  heroHighlight: string | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: siteQuery
// Query: {  "settings": *[_type == "siteSettings" && _id == "siteSettings"][0]{    email, phone, address, addressShort, location, hoursSummary, hours, socials, footerBlurb, copyrightName  },  "services": *[_type == "service"] | order(order asc){ _id, title }}
export type SiteQueryResult = {
  settings: {
    email: string | null;
    phone: string | null;
    address: string | null;
    addressShort: string | null;
    location: {
      latitude?: number;
      longitude?: number;
    } | null;
    hoursSummary: string | null;
    hours: Array<{
      days?: string;
      time?: string;
      _type: "hoursRow";
      _key: string;
    }> | null;
    socials: Array<{
      platform?: "Facebook" | "Instagram" | "LinkedIn" | "TikTok" | "X" | "YouTube";
      url?: string;
      _type: "social";
      _key: string;
    }> | null;
    footerBlurb: string | null;
    copyrightName: string | null;
  } | null;
  services: Array<{
    _id: string;
    title: string;
  }>;
};
