/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/schema.json
export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  reference?: string;
  status: "pending" | "paid" | "failed" | "shipped" | "delivered" | "cancelled" | "refunded";
  trackingNumber?: string;
  notes?: string;
  placedAt?: string;
  paidAt?: string;
  customer?: {
    name?: string;
    email?: string;
    phone?: string;
  };
  shipping?: {
    country?: string;
    state?: string;
    city?: string;
    address?: string;
    postcode?: string;
    zone?: string;
    eta?: string;
  };
  items?: Array<{
    product?: ProductReference;
    variantKey?: string;
    name?: string;
    size?: string;
    quantity?: number;
    unitPrice?: number;
    _type: "orderItem";
    _key: string;
  }>;
  subtotal?: number;
  shippingFee?: number;
  total?: number;
  payment?: {
    provider?: string;
    transactionId?: string;
    channel?: string;
    amountPaid?: number;
  };
  stockAdjusted?: boolean;
  emailsSent?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  collection?: string;
  subtitle?: string;
  garment?: string;
  tagline?: string;
  price: number;
  front: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  back: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  variants?: Array<{
    size: "XS" | "S" | "M" | "L" | "XL" | "XXL";
    stock: number;
    _type: "variant";
    _key: string;
  }>;
  description?: string;
  available?: boolean;
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type FootageAsset = {
  _id: string;
  _type: "footageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  kind: "video" | "image";
  drone?: boolean;
  location?: string;
  tags?: Array<string>;
  duration?: string;
  fps?: number;
  resolution?: "4K" | "HD";
  featured?: boolean;
  order?: number;
  poster: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  original?: R2Original;
  preview?: R2Preview;
};

export type R2Preview = {
  _type: "r2Preview";
  key?: string;
  url?: string;
  filename?: string;
  size?: number;
  contentType?: string;
};

export type R2Original = {
  _type: "r2Original";
  key?: string;
  url?: string;
  filename?: string;
  size?: number;
  contentType?: string;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  category: string;
  publishedAt: string;
  cover: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  excerpt: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  author?: string;
};

export type Client = {
  _id: string;
  _type: "client";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  logoHeight?: number;
  url?: string;
  order?: number;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  category: string;
  timecode?: string;
  still: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  videoUrl?: string;
  featured?: boolean;
  order?: number;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  tag: string;
  timecode?: string;
  description: string;
  order?: number;
};

export type SectionIntro = {
  _type: "sectionIntro";
  eyebrow: string;
  heading: string;
  linkLabel?: string;
};

export type StoreSettings = {
  _id: string;
  _type: "storeSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  open?: boolean;
  heading?: string;
  intro?: string;
  orderEmail?: string;
  nigeriaRates?: Array<{
    state:
      | "Abia"
      | "Adamawa"
      | "Akwa Ibom"
      | "Anambra"
      | "Bauchi"
      | "Bayelsa"
      | "Benue"
      | "Borno"
      | "Cross River"
      | "Delta"
      | "Ebonyi"
      | "Edo"
      | "Ekiti"
      | "Enugu"
      | "Federal Capital Territory"
      | "Gombe"
      | "Imo"
      | "Jigawa"
      | "Kaduna"
      | "Kano"
      | "Katsina"
      | "Kebbi"
      | "Kogi"
      | "Kwara"
      | "Lagos"
      | "Nasarawa"
      | "Niger"
      | "Ogun"
      | "Ondo"
      | "Osun"
      | "Oyo"
      | "Plateau"
      | "Rivers"
      | "Sokoto"
      | "Taraba"
      | "Yobe"
      | "Zamfara";
    fee?: number;
    eta?: string;
    _type: "stateRate";
    _key: string;
  }>;
  internationalZones?: Array<{
    name: string;
    countries: Array<string>;
    fee?: number;
    eta?: string;
    _type: "shippingZone";
    _key: string;
  }>;
  restOfWorldFee?: number;
  restOfWorldEta?: string;
  returnsPolicy?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  phone?: string;
  address?: string;
  addressShort?: string;
  location?: {
    latitude?: number;
    longitude?: number;
  };
  hoursSummary?: string;
  hours?: Array<{
    days?: string;
    time?: string;
    _type: "hoursRow";
    _key: string;
  }>;
  socials?: Array<{
    platform?: "YouTube" | "Instagram" | "Facebook" | "LinkedIn" | "X" | "TikTok";
    url?: string;
    _type: "social";
    _key: string;
  }>;
  footerBlurb?: string;
  copyrightName?: string;
  footageHeading?: string;
  footageIntro?: string;
  footageLicenceSummary?: string;
  footageLicence?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroHeadline: Array<string>;
  heroHighlight?: string;
  heroIntro?: string;
  heroPrimaryCta?: string;
  heroSecondaryCta?: string;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  heroVideo?: R2Preview;
  heroVideoUrl?: string;
  stats?: Array<{
    value?: string;
    label?: string;
    _type: "stat";
    _key: string;
  }>;
  services: SectionIntro;
  servicesCta?: string;
  projects: SectionIntro;
  clientsHeading?: string;
  updates: SectionIntro;
  updatesReadMore?: string;
  footage: SectionIntro;
  footageDownload?: string;
  merch: SectionIntro;
  contact: SectionIntro;
  contactIntro?: string;
  contactFormHeading?: string;
  contactSubmit?: string;
  contactImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  seoTitle?: string;
  seoDescription?: string;
  shareImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ProductReference
  | Order
  | SanityImageAssetReference
  | Product
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | FootageAsset
  | R2Preview
  | R2Original
  | Post
  | Client
  | Project
  | Service
  | SectionIntro
  | StoreSettings
  | SiteSettings
  | HomePage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries.ts
// Variable: homepageQuery
// Query: {  "page": *[_type == "homePage" && _id == "homePage"][0]{    heroEyebrow, heroHeadline, heroHighlight, heroIntro, heroPrimaryCta, heroSecondaryCta,    heroImage, heroVideoUrl, heroVideo{ url, contentType }, stats,    services, servicesCta,    projects,    clientsHeading,    updates, updatesReadMore,    footage, footageDownload,    merch,    contact, contactIntro, contactFormHeading, contactSubmit, contactImage  },  "services": *[_type == "service"] | order(order asc){ _id, title, tag, timecode, description },  "projects": *[_type == "project" && featured == true] | order(order asc)[0...4]{    _id, title, category, timecode, still, videoUrl  },  "clients": *[_type == "client"] | order(order asc){    _id, name, url, logoHeight,    logo{ ..., "dimensions": asset->metadata.dimensions{ width, height } }  },  "posts": *[_type == "post"] | order(publishedAt desc)[0...3]{    _id, title, "slug": slug.current, category, publishedAt, cover, excerpt  },  "footage": *[_type == "footageAsset"] | order(featured desc, order asc)[0...4]{    _id, title, kind, location, duration, fps, resolution, poster, featured,    "hasDownload": defined(original.key),    "previewUrl": preview.url  },  "products": *[_type == "product"] | order(order asc)[0...2]{    _id, name, garment, price, "slug": slug.current, front, back, available  }}
export type HomepageQueryResult = {
  page: {
    heroEyebrow: string | null;
    heroHeadline: Array<string>;
    heroHighlight: string | null;
    heroIntro: string | null;
    heroPrimaryCta: string | null;
    heroSecondaryCta: string | null;
    heroImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    heroVideoUrl: string | null;
    heroVideo: {
      url: string | null;
      contentType: string | null;
    } | null;
    stats: Array<{
      value?: string;
      label?: string;
      _type: "stat";
      _key: string;
    }> | null;
    services: SectionIntro;
    servicesCta: string | null;
    projects: SectionIntro;
    clientsHeading: string | null;
    updates: SectionIntro;
    updatesReadMore: string | null;
    footage: SectionIntro;
    footageDownload: string | null;
    merch: SectionIntro;
    contact: SectionIntro;
    contactIntro: string | null;
    contactFormHeading: string | null;
    contactSubmit: string | null;
    contactImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
  } | null;
  services: Array<{
    _id: string;
    title: string;
    tag: string;
    timecode: string | null;
    description: string;
  }>;
  projects: Array<{
    _id: string;
    title: string;
    category: string;
    timecode: string | null;
    still: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    videoUrl: string | null;
  }>;
  clients: Array<{
    _id: string;
    name: string;
    url: string | null;
    logoHeight: number | null;
    logo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
      dimensions: {
        width: number;
        height: number;
      } | null;
    };
  }>;
  posts: Array<{
    _id: string;
    title: string;
    slug: string;
    category: string;
    publishedAt: string;
    cover: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    excerpt: string;
  }>;
  footage: Array<{
    _id: string;
    title: string;
    kind: "image" | "video";
    location: string | null;
    duration: string | null;
    fps: number | null;
    resolution: "4K" | "HD" | null;
    poster: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    featured: boolean | null;
    hasDownload: false | true;
    previewUrl: string | null;
  }>;
  products: Array<{
    _id: string;
    name: string;
    garment: string | null;
    price: number;
    slug: string;
    front: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    back: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    available: boolean | null;
  }>;
};

// Source: src/sanity/queries.ts
// Variable: seoQuery
// Query: *[_type == "homePage" && _id == "homePage"][0]{  seoTitle, seoDescription, shareImage, heroImage, heroIntro, heroHeadline, heroHighlight}
export type SeoQueryResult = {
  seoTitle: string | null;
  seoDescription: string | null;
  shareImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  heroIntro: string | null;
  heroHeadline: Array<string>;
  heroHighlight: string | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: licenceQuery
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{  footageLicenceSummary, footageLicence}
export type LicenceQueryResult = {
  footageLicenceSummary: string | null;
  footageLicence: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: footageLibraryQuery
// Query: {  "settings": *[_type == "siteSettings" && _id == "siteSettings"][0]{    footageHeading, footageIntro, footageLicenceSummary  },  "hero": *[_type == "footageAsset" && defined(poster.asset)] | order(featured desc, order asc)[0]{ poster },  "total": count(*[    _type == "footageAsset" && defined(poster.asset)    && ($type == "all" || ($type == "drone" && drone == true) || kind == $type)    && ($search == "" || title match $search || location match $search || count(tags[@ match $search]) > 0)  ]),  "items": *[    _type == "footageAsset" && defined(poster.asset)    && ($type == "all" || ($type == "drone" && drone == true) || kind == $type)    && ($search == "" || title match $search || location match $search || count(tags[@ match $search]) > 0)  ] | order(featured desc, order asc, _createdAt desc)[$start...$end]{    _id, title, kind, location, duration, fps, resolution,    poster{ ..., "dimensions": asset->metadata.dimensions{ width, height } },    "hasDownload": defined(original.key),    "previewUrl": preview.url  }}
export type FootageLibraryQueryResult = {
  settings: {
    footageHeading: string | null;
    footageIntro: string | null;
    footageLicenceSummary: string | null;
  } | null;
  hero: {
    poster: {
      asset: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
  } | null;
  total: number;
  items: Array<{
    _id: string;
    title: string;
    kind: "image" | "video";
    location: string | null;
    duration: string | null;
    fps: number | null;
    resolution: "4K" | "HD" | null;
    poster: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
      dimensions: {
        width: number;
        height: number;
      } | null;
    };
    hasDownload: false | true;
    previewUrl: string | null;
  }>;
};

// Source: src/sanity/queries.ts
// Variable: storeStatusQuery
// Query: *[_id == "storeSettings"][0]{ open }
export type StoreStatusQueryResult =
  | {
      open: null;
    }
  | {
      open: boolean | null;
    }
  | null;

// Source: src/sanity/queries.ts
// Variable: storeQuery
// Query: {  "settings": *[_id == "storeSettings"][0]{ open, heading, intro },  "products": *[_type == "product"] | order(order asc){    _id, name, "slug": slug.current, collection, subtitle, garment, price, available, front, back,    "inStock": count(variants[stock > 0]) > 0  }}
export type StoreQueryResult = {
  settings:
    | {
        open: null;
        heading: null;
        intro: null;
      }
    | {
        open: boolean | null;
        heading: string | null;
        intro: string | null;
      }
    | null;
  products: Array<{
    _id: string;
    name: string;
    slug: string;
    collection: string | null;
    subtitle: string | null;
    garment: string | null;
    price: number;
    available: boolean | null;
    front: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    back: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    inStock: boolean | null;
  }>;
};

// Source: src/sanity/queries.ts
// Variable: productQuery
// Query: {  "settings": *[_id == "storeSettings"][0]{ open },  "product": *[_type == "product" && slug.current == $slug][0]{    _id, name, "slug": slug.current, collection, subtitle, garment, tagline, price, available, description,    front, back, variants[]{ _key, size, stock }  }}
export type ProductQueryResult = {
  settings:
    | {
        open: null;
      }
    | {
        open: boolean | null;
      }
    | null;
  product: {
    _id: string;
    name: string;
    slug: string;
    collection: string | null;
    subtitle: string | null;
    garment: string | null;
    tagline: string | null;
    price: number;
    available: boolean | null;
    description: string | null;
    front: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    back: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    variants: Array<{
      _key: string;
      size: "L" | "M" | "S" | "XL" | "XS" | "XXL";
      stock: number;
    }> | null;
  } | null;
};

// Source: src/sanity/queries.ts
// Variable: productSlugsQuery
// Query: *[_type == "product" && defined(slug.current)].slug.current
export type ProductSlugsQueryResult = Array<string>;

// Source: src/sanity/queries.ts
// Variable: checkoutQuery
// Query: *[_id == "storeSettings"][0]{  open, nigeriaRates[]{ state, fee, eta }, internationalZones[]{ name, countries, fee, eta }, restOfWorldFee, restOfWorldEta}
export type CheckoutQueryResult =
  | {
      open: null;
      nigeriaRates: null;
      internationalZones: null;
      restOfWorldFee: null;
      restOfWorldEta: null;
    }
  | {
      open: boolean | null;
      nigeriaRates: Array<{
        state:
          | "Abia"
          | "Adamawa"
          | "Akwa Ibom"
          | "Anambra"
          | "Bauchi"
          | "Bayelsa"
          | "Benue"
          | "Borno"
          | "Cross River"
          | "Delta"
          | "Ebonyi"
          | "Edo"
          | "Ekiti"
          | "Enugu"
          | "Federal Capital Territory"
          | "Gombe"
          | "Imo"
          | "Jigawa"
          | "Kaduna"
          | "Kano"
          | "Katsina"
          | "Kebbi"
          | "Kogi"
          | "Kwara"
          | "Lagos"
          | "Nasarawa"
          | "Niger"
          | "Ogun"
          | "Ondo"
          | "Osun"
          | "Oyo"
          | "Plateau"
          | "Rivers"
          | "Sokoto"
          | "Taraba"
          | "Yobe"
          | "Zamfara";
        fee: number | null;
        eta: string | null;
      }> | null;
      internationalZones: Array<{
        name: string;
        countries: Array<string>;
        fee: number | null;
        eta: string | null;
      }> | null;
      restOfWorldFee: number | null;
      restOfWorldEta: string | null;
    }
  | null;

// Source: src/sanity/queries.ts
// Variable: returnsQuery
// Query: *[_id == "storeSettings"][0]{ returnsPolicy }
export type ReturnsQueryResult =
  | {
      returnsPolicy: null;
    }
  | {
      returnsPolicy: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
    }
  | null;

// Source: src/sanity/queries.ts
// Variable: footageTitleQuery
// Query: *[_type == "footageAsset" && _id == $id][0]{ _id, title, kind }
export type FootageTitleQueryResult = {
  _id: string;
  title: string;
  kind: "image" | "video";
} | null;

// Source: src/sanity/queries.ts
// Variable: siteQuery
// Query: {  "settings": *[_type == "siteSettings" && _id == "siteSettings"][0]{    email, phone, address, addressShort, location, hoursSummary, hours, socials, footerBlurb, copyrightName,    footageLicenceSummary  },  "services": *[_type == "service"] | order(order asc){ _id, title }}
export type SiteQueryResult = {
  settings: {
    email: string | null;
    phone: string | null;
    address: string | null;
    addressShort: string | null;
    location: {
      latitude?: number;
      longitude?: number;
    } | null;
    hoursSummary: string | null;
    hours: Array<{
      days?: string;
      time?: string;
      _type: "hoursRow";
      _key: string;
    }> | null;
    socials: Array<{
      platform?: "Facebook" | "Instagram" | "LinkedIn" | "TikTok" | "X" | "YouTube";
      url?: string;
      _type: "social";
      _key: string;
    }> | null;
    footerBlurb: string | null;
    copyrightName: string | null;
    footageLicenceSummary: string | null;
  } | null;
  services: Array<{
    _id: string;
    title: string;
  }>;
};
